import {
  faUser,
  faLock,
  faAt,
  faHandPointLeft,
  faHome,
  faUserPlus,
  faDatabase,
  faSchool,
  faChartLine,
  faInfo,
  faIcons,
  faPlusSquare,
  faSignOutAlt,
  faWindowClose,
  faGraduationCap,
  faMinus,
  faEdit,
  faPlus,
  faUserCircle,
  faArrowRight,
  faCircleNotch,
  faCheck,
  faChartArea,
  faBell,
  faTag,
  faAward,
  faCheckCircle,
  faExclamationCircle
} from "@fortawesome/free-solid-svg-icons";
import { library } from "@fortawesome/fontawesome-svg-core";
import { fab } from "@fortawesome/free-brands-svg-icons";
const iconsLibrary = library.add(
  fab,
  faUser,
  faLock,
  faAt,
  faHandPointLeft,
  faHome,
  faUserPlus,
  faDatabase,
  faSchool,
  faChartLine,
  faInfo,
  faIcons,
  faPlusSquare,
  faSignOutAlt,
  faGraduationCap,
  faWindowClose,
  faMinus,
  faEdit,
  faPlus,
  faUserCircle,
  faArrowRight,
  faCircleNotch,
  faCheck,
  faChartArea,
  faBell,
  faTag,
  faAward,
  faCheckCircle,
  faExclamationCircle
);

export default iconsLibrary;
